### ISSUE TITLE
Set default R for Context

### ISSUE THREAD

**Issue by jonhoo** [gimli-rs/addr2line#109]
If we expect users to _often_ end up with `Context<EndianRcSlice<RunTimeEndian>>`, should we just make that the default type? As in:
```rust
pub struct Context<R = EndianRcSlice<RunTimeEndian>> {}
```
That would save users of the library to explicitly type out the full type for `Context` in the common case!

**Comment by philipc** [comment]
Makes sense since that's what `Context::new` returns. You can also do a type alias in your code though.

**Comment by jonhoo** [comment]
Oh, sure, I could totally do it in my code, but I guess the question is whether it makes sense to just include it directly in `addr2line`?

**Comment by philipc** [comment]
Fixed by #111
