### ISSUE TITLE
Expose inlining chains, not just last step

### ISSUE THREAD

**Issue by jonhoo** [gimli-rs/addr2line#11]
`Mapping::locate()` currently exposes only the *closest* function to a given address, which means that any address will only be resolved to the deepest inlined function that contains it. It would be better if `locate` returned the full chain of function ancestors for an address.

**Comment by cuviper** [comment]
This would be like binutils `addr2line -i` right?  And `eu-addr2line` has this too.

**Comment by jonhoo** [comment]
@cuviper that's exactly right.

**Comment by fitzgen** [comment]
Now that `backtrace-rs` is using this crate (behind a feature flag) it seems even more important to fix this, as we backtraces will be incomplete without it.

Filed https://github.com/alexcrichton/backtrace-rs/issues/67 on the `backtrace-rs` side.

**Comment by jonhoo** [comment]
I think we may want to consider making `Mapping::locate` return a `struct` instead of an increasingly long tuple along with this change. Otherwise, how would anyone remember that `.3` of the returned value is the call chain?

**Comment by fitzgen** [comment]
Indeed. Ideally, we would return an iterator that didn't do work unless it was asked for too.

**Comment by philipc** [comment]
Fixed by #64
