### ISSUE TITLE
`context_new_with_functions` benchmark is same as `context_new_location`

### ISSUE THREAD

**Issue by RReverser** [gimli-rs/addr2line#135]
Looks like ever since https://github.com/gimli-rs/addr2line/commit/734bf1f5ddb5c761d8ec4848aa93def3c66ddc42#diff-afb2ab3fe17077dcacb9d8b9f1546945 these two benchmarks became exactly the same, since `parse_functions` became private and was just removed from the benchmark code.

I'm not sure if it can be changed to still benchmark something separate, or whether it should be just removed at this point.

**Comment by philipc** [comment]
> I'm not sure if it can be changed to still benchmark something separate, or whether it should be just removed at this point.

I have some benchmarks that measure only `parse_lines`/`parse_functions` which I'll commit once I have time.

**Comment by philipc** [comment]
I've added those in #140
