### ISSUE TITLE
Add location_iter api

### ISSUE THREAD

**Issue by eqv** [gimli-rs/addr2line#149]
For some use-cases it would be super helpful to be able to iterate over all units/frames or locations in the binary. This could be accomplished simply by exposing the  `Lines` struct.

**Comment by philipc** [comment]
Can you give an example of this use case?

Without knowing more, I think you may be better off using gimli directly. Exposing `Lines` is undesirable because the problem this crate solves is how to cache the data efficiently for address lookups, and we don't want to be locked into a particular algorithm (and indeed, `Lines` is something that was changed recently).

**Comment by eqv** [comment]
I'm doing mass lookups (think: all instruction), in a linear manner to build a complete instruction => line mapping. This has two usecase: One to obtain a map of all lines that contributed to the binary, and two, to turn a large set of instruction level traces into source level traces. Doing a binary search for each address is terrible slow in this case.
By iterating directly over the ranges, I can build a hashmap Addr-> sourcfile/line, which cuts the computation time from nearly half an hour to seconds. 
 This crate already does a lot work to get all the gimli data into a format that I can use (sorted array, anything iteratable really). ATM I simply copied most of this crate into my code to access the internal representation, however this makes it much harder to keep up with bugfixes in addr2line and gimli.  If you think this usecase is probably uncommon, feel free to close this issue. 
Otherwise, I would probably submit a pull request for a API that exposes an iterator on `LineRow` or a similar data type, to limit exposing implementation details.

**Comment by philipc** [comment]
How do you plan to handle the inline function information? I'm not sure that a hashmap is suitable for that.

If adding the iterator is relatively small, then I'm fine with merging that.

**Comment by philipc** [comment]
Closing, see #153.
