### ISSUE TITLE
Use `cpp_demangle` crate for demangling C++ symbols, once its ready

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/addr2line#17]
Ongoing WIP over here: https://github.com/fitzgen/cpp_demangle

**Comment by fitzgen** [comment]
Also, we could move that repo into the `gimli-rs` org if others are interested in helping maintain it once @JimBlandy and I get it generally working. I could see it fitting into the org, or not, either way.

Thoughts @philipc @jonhoo @tromey ?

**Comment by tromey** [comment]
I think it makes sense as part of gimli, since you often want demangling when you use a dwarf reader.
