### ISSUE TITLE
Slow find_frames on XUL.dSYM, in unit.parse_functions

### ISSUE THREAD

**Issue by mstange** [gimli-rs/addr2line#171]
I'm trying to get inline call stacks for around 60000 addresses from the Firefox-on-Mac `XUL` library, from a `XUL.dSYM` bundle. It takes 2 minutes. That's 2ms per address. [Instruments profile](https://drive.google.com/file/d/1U4DG3nduoHDqwDxRF10GOqmtV12lIOAw/view?usp=sharing)

Doing the same on a Linux libxul.so takes 0.8ms per address, and for PDBs it takes 0.19ms per address.

It would be great if this could be made faster. Once the Firefox profiler supports displaying inline call stacks, I want to use this code to get the inline frame information for local builds, and it would be great to not regress symbolication times too much compared to the current state without inline callstacks.

Steps to reproduce:

```
git clone https://github.com/mstange/profiler-get-symbols/
cd profiler-get-symbols/
git checkout 8152ad4968d847763df3e79388150d87ab214c7e
cargo run -p benchmarks --release
```

Plan around 10-20min for the first run, because it is slow to compile and downloads large resources. Most importantly, this step creates `big-benchmark-fixtures/macos-ci/XUL.dSYM`.

Then run the following to run just the dSYM test (this is the command that obtains inline callstacks for 59736 addresses from XUL.dSYM):

```
cargo run --release -p query-api -- big-benchmark-fixtures/macos-ci/ /symbolicate/v6a1 @fixtures/requests/macos-ci-xul.json > /dev/null
```

Profiling in Instruments reveals that most of the time is spent in `unit.parse_functions`. It seems that if many addresses fall into the same unit (?) we might be doing a lot of duplicated work.

<img width="1045" alt="Screen Shot 2020-05-18 at 8 34 11 PM" src="https://user-images.githubusercontent.com/961291/82273662-15c4ba80-994c-11ea-97b4-db28e9f69949.png">
<img width="1045" alt="Screen Shot 2020-05-18 at 8 38 10 PM" src="https://user-images.githubusercontent.com/961291/82273665-18271480-994c-11ea-8779-dc9d2a17a263.png">

**Comment by philipc** [comment]
> Profiling in Instruments reveals that most of the time is spent in unit.parse_functions. It seems that if many addresses fall into the same unit (?) we might be doing a lot of duplicated work.

Note that `parse_functions` caches its result, so it may be called many times, but will only do the work once per unit.

I'll have a look into it, but I have already tried to optimize this code as much as I can.

**Comment by mstange** [comment]
Oh, I didn't realize that. Thanks.

**Comment by philipc** [comment]
It looks like the problem is this loop over the units: https://github.com/gimli-rs/addr2line/blob/a8757e5275ddc7c11c360a1b0c645bcbc2ae6c43/src/lib.rs#L652-L666

I don't think this is a code path that has shown up in my past profiles, but it appears to be due to LTO causing use of `DW_FORM_ref_addr`. We can make this faster by changing to a binary search instead of a loop, but it's still going to be slower than without LTO.

**Comment by mstange** [comment]
Very nice! This seems to have sped up my benchmark by 5x. 2min -> ~25s
It didn't improve the performance for object files, though, as expected.

**Comment by mstange** [comment]
The patches in #176 further improve the benchmark by about 2x, to ~12-15s.

**Comment by philipc** [comment]
Sorry if I closed this prematurely, reopen it if you feel it is warranted.

**Comment by mstange** [comment]
Oh, no worries. The 5x improvement from your change was definitely reason enough to close this.
