### ISSUE TITLE
Many addresses are missing file + line information

### ISSUE THREAD

**Issue by mstange** [gimli-rs/addr2line#174]
When using addr2line to find file and line information from a local Firefox build on macOS, many addresses end up without file or line information. Here's one example:

 1. Download [nsEmbedFunctions.o](https://drive.google.com/file/d/1-4Hx_d7icTdzSMw5LdslCnYiL7Qn0Iru/view?usp=sharing).
 2. Look up addresses 0x104d and 0x1052.

Result:

``` 
cargo run --release --example addr2line -- -C -f -i --exe /Users/mstange/code/obj-m-opt/toolkit/xre/nsEmbedFunctions.o 0x104d 0x1052
    Finished release [optimized + debuginfo] target(s) in 0.18s
     Running `target/release/examples/addr2line -C -f -i --exe /Users/mstange/code/obj-m-opt/toolkit/xre/nsEmbedFunctions.o 0x104d 0x1052`
XRE_InitChildProcess(int, char**, XREChildData const*)
??:?
XRE_InitChildProcess(int, char**, XREChildData const*)
??:?
```

lldb finds file + line + column information for these addresses correctly: `nsEmbedFunctions.cpp:740:34`.

(Edit: unnecessary details elided, see next comment for `atos` getting it right)

**Comment by mstange** [comment]
More importantly, `atos` also finds the information:

```
atos -o /Users/mstange/code/obj-m-opt/toolkit/xre/nsEmbedFunctions.o 0x104d 0x1051 0x1052
XRE_InitChildProcess(int, char**, XREChildData const*) (in nsEmbedFunctions.o) (nsEmbedFunctions.cpp:740)
XRE_InitChildProcess(int, char**, XREChildData const*) (in nsEmbedFunctions.o) (nsEmbedFunctions.cpp:740)
XRE_InitChildProcess(int, char**, XREChildData const*) (in nsEmbedFunctions.o) (nsEmbedFunctions.cpp:744)
```

**Comment by philipc** [comment]
Does this only occur for object files? We don't currently process relocations.

**Comment by mstange** [comment]
Ah, yes, it's likely that this only happens for object files.
If I run dsymutil (which takes 3.5 minutes) and look up the corresponding address in XUL.dSYM, addr2line does find the correct filename + line information.

How hard would it be to add support for object files?

**Comment by philipc** [comment]
The dwarfdump example in gimli can [handle them](https://github.com/gimli-rs/gimli/blob/ea707d784e1a695255f049489a49c9f2f6cb6abc/examples/dwarfdump.rs#L156), so not hard to do in the addr2line example. I assume you want this in a library you can use too though?

**Comment by philipc** [comment]
We'll want to implement this for split debuginfo support in backtrace-rs too.

**Comment by mstange** [comment]
Not sure I completely understand the question, but I'd want `addr2line::Context::find_frames` to find this information in object files. [Here's where I'm calling it](https://github.com/mstange/profiler-get-symbols/blob/2bbe03b1672f9c07147a7ed0e65c2c14a747df4c/lib/src/dwarf.rs#L37).

(And I have homegrown split debuginfo code [here](https://github.com/mstange/profiler-get-symbols/blob/2bbe03b1672f9c07147a7ed0e65c2c14a747df4c/lib/src/macho.rs#L361-L409) which I'd love to replace with something from `object`.)

**Comment by philipc** [comment]
`find_frames` will work as long as the `Reader` supports relocations. You're currently [using `EndianSlice`](https://github.com/mstange/profiler-get-symbols/blob/2bbe03b1672f9c07147a7ed0e65c2c14a747df4c/lib/src/dwarf.rs#L154), which can't handle relocations. `dwarfdump` has its own [`Reader` implementation](https://github.com/gimli-rs/gimli/blob/ea707d784e1a695255f049489a49c9f2f6cb6abc/examples/dwarfdump.rs#L245), so that will need to be put in a library somewhere. It relies on `object` though, and `gimli` has tried to remain independent of `object`.

Thanks for the split debuginfo link, I plan to add that to `object` soon. I'm also aware of an implementation in https://github.com/mozilla/fix-stacks

**Comment by mstange** [comment]
Ooohh, I see. Thanks for the pointers!

**Comment by mstange** [comment]
I think I have everything I need then.

**Comment by mstange** [comment]
The problem doesn't seem to be related to relocations. If I comment out the call to `add_relocations` in the dwarfdump example, it still finds the lines.

And `cargo run --release --example simple_line -- /Users/mstange/code/obj-m-opt/toolkit/xre/nsEmbedFunctions.o` also works, and from what I can tell the `simple_line` example doesn't seem to handle relocations:

```
...
104a /Users/mstange/code/mozilla/toolkit/xre/nsEmbedFunctions.cpp:740:34
1052 /Users/mstange/code/mozilla/toolkit/xre/nsEmbedFunctions.cpp:744:16
...
```

I'm looking into it some more.

**Comment by mstange** [comment]
It's because of this check:

https://github.com/gimli-rs/addr2line/blob/a8757e5275ddc7c11c360a1b0c645bcbc2ae6c43/src/lib.rs#L478

The first line row starts at address 0 in this object. This check makes us ignore all the rows.

**Comment by philipc** [comment]
Ah right. So I'm pretty sure we need that check for executables, because I think the linker leaves the address at 0 for functions that are omitted, instead of deleting the line information (and same for DIEs). So maybe we need to set a flag on `Context` to say whether it is an object or executable file.

**Comment by philipc** [comment]
That check was added based on the investigation I did in https://github.com/gimli-rs/addr2line/issues/67#issuecomment-345502244.

This was when we were still using an interval tree, and so doing a lookup of 0 resulting in poor behaviour. It might be safe to delete the check now. I'll look into it a bit more.

**Comment by philipc** [comment]
Deleting the 0 check looks okay and matches other tools. I'll do a PR for that once #178 is merged.

**Comment by mstange** [comment]
Awesome, thank you!
