### ISSUE TITLE
Are column values of 0 ever exposed?

### ISSUE THREAD

**Issue by mstange** [gimli-rs/addr2line#179]
I came across `ColumnType::LeftEdge` when reading gimli code recently, and it made me wonder how function calls at the start of a line are exposed by addr2line. There's a piece of code that turns 0 into None.

**Comment by philipc** [comment]
Yes, I think that `None` for the column means start of line, and we should document that better.

I think that we may not be correctly handling line numbers of 0 though. I'll have to check, but I think this means that none of the location info is valid.

**Comment by bjorn3** [comment]
http://dwarfstd.org/doc/DWARF5.pdf table 6.3:

> register name | meaning
> --- | ---
> [...] | [...]
> column | An unsigned integer indicating a column number within a source line. Columns are numbered beginning at 1. The value 0 is reserved to indicate that a statement begins at the “left edge” of the line.
> [...] | [...]

**Comment by philipc** [comment]
Right, but is there any useful distinction between those two? Do any other tools make that distinction?

**Comment by bjorn3** [comment]
LLDB doesn't show the underline for the current column when it is not specified. I think it does show it for the "left edge".

**Comment by mstange** [comment]
So yeah, if "not specified" and "left edge" are both possible, then we shouldn't expose "left edge" as None.

**Comment by philipc** [comment]
>  I think it does show it for the "left edge".

Can you verify this please.

I'm happy to expose "left edge" if it has meaning, but I looked in llvm, lldb, gcc and gdb, and while I haven't looked exhaustively, I haven't found evidence that there is a difference between "not specified" and "left edge". They all simply use a u16 or u32 for columns, and 0 means not specified.
