### ISSUE TITLE
Land script to bench and graph running time and memory usage

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/addr2line#18]
@jonhoo could you open a PR to include the script you used to make those graphs? I'd like to add a comparison to elfutils' `addr2line`.

Would also be nice to get a `#[bench]` version, but that's a bit orthogonal.

**Comment by jonhoo** [comment]
Yeah, the scripts I wrote aren't very `#[bench]` compatible at the moment. It also requires some different infrastructure, as we also need a decent binary target, but we could probably adapt the tricksy code from the tests somehow.

**Comment by jonhoo** [comment]
Fixed in #20.
