### ISSUE TITLE
Maybe adjust the section about benchmarking in the readme

### ISSUE THREAD

**Issue by mstange** [gimli-rs/addr2line#180]
The readme currently says "We haven't done extensive benchmarking (yet)", which initially made me assume that not much effort had been spent on performance so far. It would be nice to change that paragraph a little bit so that readers know what to expect of the performance.

**Comment by philipc** [comment]
Good idea. I think also I'll delete the comparison with other tools because it's hard to do correctly and it's not something I want to keep up to date.
