### ISSUE TITLE
addr2line doesn't build anymore w/ gimli/master

### ISSUE THREAD

**Issue by gabrielesvelto** [gimli-rs/addr2line#189]
gimli's revision [5b156848a66967dbc51278c3c5f0c832e2c53f88](https://github.com/gimli-rs/gimli/commit/5b156848a66967dbc51278c3c5f0c832e2c53f88) changed how unit offsets are represented and this broke addr2line which relied on `UnitHeader.offset()` to return a `DebugInfoOffset` struct to order the list of units. I guess that the fix is to teach addr2line about `DebugInfo` and `DebugTypes` units.

**Comment by philipc** [comment]
Right. Unless there is an immediate need, this will get fixed after releasing a new gimli version (whenever that happens).
