### ISSUE TITLE
OffsetOutOfBounds on C++ binaries

### ISSUE THREAD

**Issue by SWW13** [gimli-rs/addr2line#192]
For C++ binaries with classes I get `OffsetOutOfBounds` errors, which most likely originate from `addr2line`.

Steps to reproduce:
```
$ cargo install addr2line --example addr2line
$ addr2line --functions --exe test-ooob 0x1172
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OffsetOutOfBounds', /path/.cargo/registry/src/github.com-1ecc6299db9ec823/addr2line-0.13.0/examples/addr2line.rs:183:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The binaries seem to be fine, at least binutils works fine on them:
```
$ /usr/bin/addr2line --functions --exe test-ooob 0x1172 # 
_ZN9SomeClass4mainEv
/path/builddir/../test-ooob.cpp:14
$ /usr/bin/addr2line --version
GNU addr2line (GNU Binutils) 2.35
```

`gimli` also seems to have to problems finding the debug info:
```
$ cargo install gimli --example dwarfdump
$ dwarfdump test-ooob
< 2><0x000023af>      DW_TAG_subprogram
                        DW_AT_external              yes
                        DW_AT_name                  main
                        DW_AT_decl_file             0x00000029 /path/builddir/../test-ooob.cpp
                        DW_AT_decl_line             0x00000009
                        DW_AT_decl_column           0x00000007
                        DW_AT_linkage_name          _ZN9SomeClass4mainEv
                        DW_AT_accessibility         DW_ACCESS_public
                        DW_AT_declaration           yes
                        DW_AT_object_pointer        0x000023c0<.debug_info+0x000024e5>
```

Attached sources, to build them run:
```
$ meson builddir/
$ cd builddir/
$ ninja
$ file test-*
```

[example.zip](https://github.com/gimli-rs/addr2line/files/5275239/example.zip)

---

Additional info:
```
$ rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)
$ cargo --version
cargo 1.46.0 (149022b1d 2020-07-17)
$ uname -a
Linux $HOST 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux
$ g++ --version
g++ (GCC) 10.2.0
```

---

On a side note, by further reducing the example I found another error, which is likely related:
```
$ addr2line --functions --exe test-neago 0x1122
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoEntryAtGivenOffset', /path/.cargo/registry/src/github.com-1ecc6299db9ec823/addr2line-0.13.0/examples/addr2line.rs:183:53

$ addr2line --functions --exe test-neago 0x1122
_ZN9SomeClass4mainEv
/path/builddir/../test-neago.cpp:9
```

**Comment by philipc** [comment]
Thanks for the detailed bug report! Both of those errors have the same cause. I'll have a fix for this soon.

**Comment by philipc** [comment]
> gimli also seems to have to problems finding the debug info:
> 
> $ cargo install gimli --example dwarfdump
> $ dwarfdump test-ooob
> < 2><0x000023af>      DW_TAG_subprogram
>                         DW_AT_external              yes
>                         DW_AT_name                  main
>                         DW_AT_decl_file             0x00000029 /path/builddir/../test-ooob.cpp
>                         DW_AT_decl_line             0x00000009
>                         DW_AT_decl_column           0x00000007
>                         DW_AT_linkage_name          _ZN9SomeClass4mainEv
>                         DW_AT_accessibility         DW_ACCESS_public
>                         DW_AT_declaration           yes
>                         DW_AT_object_pointer        0x000023c0<.debug_info+0x000024e5>

Is that the full output you are getting? I wasn't able to reproduce any problem here (I get all the output that I would expect). Note that I'm using g++ 9.3.0 though.

**Comment by SWW13** [comment]
Sorry, I meant to write _gimli also seems to have **no** problems_.
