### ISSUE TITLE
crates.io lists addr2line as a command when it is a library

### ISSUE THREAD

**Issue by yurivict** [gimli-rs/addr2line#197]
Here https://crates.io/crates/addr2line the project erroneously has the category "Command line utilities".

Could you please remove it?

Thanks,
Yuri

**Comment by bjorn3** [comment]
The `addr2line` example is a command line utility. Maybe it shluld be changed from example to main executable?

**Comment by philipc** [comment]
> The addr2line example is a command line utility. Maybe it shluld be changed from example to main executable?

In its current state, that example is intended only as an example and for testing the library. It could be changed to a main executable if someone is willing to do the work to maintain it as a command suitable for end users. Otherwise, I'll delete the category when doing the next release.

**Comment by yurivict** [comment]
Please just delete the category if it is mainly a library.

Thanks!
