### ISSUE TITLE
find_location_range returns duplicate addresses

### ISSUE THREAD

**Issue by jsgf** [gimli-rs/addr2line#198]
It works OK on small ranges but large ranges make it return the same locations multiple times.

Looking into it - I'm guessing it's having problems spanning units or something.

**Comment by philipc** [comment]
Have you checked if these addresses are actually duplicated in the DWARF?

**Comment by jsgf** [comment]
@philipc - No the DWARF is OK. It's that the same Unit can appear multiple times with different ranges, and so the iterator can return it repeatedly, which caused the whole thing to be repeatedly re-iterated. The fix pays attention to the subrange and only iterates that.
