### ISSUE TITLE
Consider ignoring non-end-sequence line number program entries with line == 0

### ISSUE THREAD

**Issue by khuey** [gimli-rs/addr2line#205]
I've seen clang produce line number program output like

```
0x008d7a75  [1304, 9] NS
0x008d7a8f  [   0, 0]
0x008d7a9b  [1168, 9] NS
0x008d7ab5  [   0, 0]
0x008d7ac1  [1174, 9] NS
0x008d7adb  [   0, 0]
0x008d7ae7  [1309, 5] NS
0x008d7b01  [   0, 0]
```

Both binutils and gimli's addr2line will successfully attribute `0x008d7ae7` to a line but fail to attribute `0x008d7b01` to a specific line. gdb, on the other hand, will attribute them both to the same line, because gdb explicitly ignores LNP entries where the row is zero (see https://github.com/bminor/binutils-gdb/blob/f5b2658b0fbef02a855b7bb7288de051cc687237/gdb/dwarf2/read.c#L21598)

**Comment by philipc** [comment]
My reading of https://github.com/bminor/binutils-gdb/commit/876518dd0a0b6fd6f4ad0a0b247db0d6a267db27 is that the behaviour in this crate is correct, and gdb is only ignoring them as a workaround.

**Comment by philipc** [comment]
Tested that lldb also treats this as having no line number:
```
Note: this address is compiler-generated code in function main that has no source code associated with it.
```

gdb did display a line for this address, but as said above I think it is wrong.
