### ISSUE TITLE
`Context` is not `Send` anymore

### ISSUE THREAD

**Issue by koute** [gimli-rs/addr2line#218]
In `addr2line` 0.14.1 [`Context` implemented `Send`](https://docs.rs/addr2line/0.14.1/addr2line/struct.Context.html#impl-Send), and now in 0.15.1 [it doesn't](https://docs.rs/addr2line/0.15.1/addr2line/struct.Context.html#impl-Send). I don't see anything about this in the changelog. Was this intended?

**Comment by philipc** [comment]
No that wasn't intended. One thing that has changed is it now includes an `Arc<Dwarf>`, but I didn't think that would change `Send`. This isn't something I'm very familiar with though.

**Comment by philipc** [comment]
There's also an `Arc<ResDwarf>` which contains a `LazyCell` which isn't `Sync`, so that `Arc` isn't `Send`, if I understand correctly.

**Comment by philipc** [comment]
Can you check if #219 fixes this for you?

**Comment by koute** [comment]
From what I can see it does!

Could we perhaps add a test for this so that it doesn't regress in the future? Maybe something like this?

```rust
#[test]
fn test_is_send() {
    fn assert_is_send<T: Send>() {}
    assert_is_send::<addr2line::Context<addr2line::gimli::read::EndianSlice<addr2line::gimli::LittleEndian>>>();
}
```

**Comment by philipc** [comment]
Sure, I'll add that and do a release tomorrow.

So we still have a change where it now requires the `Reader` to be both `Sync` and `Send`, while in 0.14.1 it only required `Send`. Hopefully that is going to be acceptable, otherwise we have to change something for `gimli::Dwarf::sup`.

**Comment by koute** [comment]
> So we still have a change where it now requires the `Reader` to be both `Sync` and `Send`, while in 0.14.1 it only required `Send`. Hopefully that is going to be acceptable, otherwise we have to change something for `gimli::Dwarf::sup`.

That's a consequence of two things:

1. [gimli::Dwarf in 0.23 only requiring Send](https://docs.rs/gimli/0.23.0/gimli/read/struct.Dwarf.html#impl-Send) and now [in 0.24 it also requires Sync](https://docs.rs/gimli/0.24.0/gimli/read/struct.Dwarf.html#impl-Send), but that's fixable like this:

```patch
diff --git a/src/read/dwarf.rs b/src/read/dwarf.rs
index fee8b42..b864f31 100644
--- a/src/read/dwarf.rs
+++ b/src/read/dwarf.rs
@@ -1,5 +1,5 @@
 use alloc::string::String;
-use alloc::sync::Arc;
+use alloc::boxed::Box;
 
 use crate::common::{
     DebugAddrBase, DebugAddrIndex, DebugInfoOffset, DebugLineStrOffset, DebugLocListsBase,
@@ -56,7 +56,7 @@ pub struct Dwarf<R> {
     pub file_type: DwarfFileType,
 
     /// The DWARF sections for a supplementary object file.
-    pub sup: Option<Arc<Dwarf<R>>>,
+    pub sup: Option<Box<Dwarf<R>>>,
 }
 
 impl<T> Dwarf<T> {
@@ -106,7 +106,7 @@ impl<T> Dwarf<T> {
     where
         F: FnMut(SectionId) -> core::result::Result<T, E>,
     {
-        self.sup = Some(Arc::new(Self::load(section)?));
+        self.sup = Some(Box::new(Self::load(section)?));
         Ok(())
     }
 
@@ -154,13 +154,13 @@ impl<T> Dwarf<T> {
             locations: self.locations.borrow(&mut borrow),
             ranges: self.ranges.borrow(&mut borrow),
             file_type: self.file_type,
-            sup: self.sup().map(|sup| Arc::new(sup.borrow(borrow))),
+            sup: self.sup().map(|sup| Box::new(sup.borrow(borrow))),
         }
     }
 
     /// Return a reference to the DWARF sections for supplementary object file.
     pub fn sup(&self) -> Option<&Dwarf<T>> {
-        self.sup.as_ref().map(Arc::as_ref)
+        self.sup.as_ref().map(Box::as_ref)
     }
 }
```

2. In `ResDwarf` the `sections` uses an `Arc`, that can be fixed like this I guess:

```patch
diff --git a/src/lib.rs b/src/lib.rs
index 3236a34..ba97d10 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -44,7 +44,6 @@ use alloc::boxed::Box;
 #[cfg(feature = "object")]
 use alloc::rc::Rc;
 use alloc::string::{String, ToString};
-use alloc::sync::Arc;
 use alloc::vec::Vec;
 
 use core::cmp::{self, Ordering};
@@ -185,11 +184,7 @@ impl<R: gimli::Reader> Context<R> {
     /// Construct a new `Context` from an existing [`gimli::Dwarf`] object.
     #[inline]
     pub fn from_dwarf(sections: gimli::Dwarf<R>) -> Result<Self, Error> {
-        let mut dwarf = ResDwarf::parse(Arc::new(sections))?;
-        dwarf.sup = match dwarf.sections.sup.clone() {
-            Some(sup_sections) => Some(Box::new(ResDwarf::parse(sup_sections)?)),
-            None => None,
-        };
+        let dwarf = ResDwarf::parse(sections)?;
         Ok(Context { dwarf })
     }
 
@@ -365,12 +360,12 @@ struct UnitRange {
 struct ResDwarf<R: gimli::Reader> {
     unit_ranges: Vec<UnitRange>,
     units: Vec<ResUnit<R>>,
-    sections: Arc<gimli::Dwarf<R>>,
+    sections: Box<gimli::Dwarf<R>>,
     sup: Option<Box<ResDwarf<R>>>,
 }
 
 impl<R: gimli::Reader> ResDwarf<R> {
-    fn parse(sections: Arc<gimli::Dwarf<R>>) -> Result<Self, Error> {
+    fn parse(mut sections: gimli::Dwarf<R>) -> Result<Self, Error> {
         // Find all the references to compilation units in .debug_aranges.
         // Note that we always also iterate through all of .debug_info to
         // find compilation units, because .debug_aranges may be missing some.
@@ -504,11 +499,16 @@ impl<R: gimli::Reader> ResDwarf<R> {
             i.max_end = max;
         }
 
+        let sup = match sections.sup.take() {
+            Some(sup_sections) => Some(Box::new(ResDwarf::parse(*sup_sections)?)),
+            None => None,
+        };
+
         Ok(ResDwarf {
             units: res_units,
             unit_ranges,
-            sections,
-            sup: None,
+            sections: Box::new(sections),
+            sup,
         })
     }
 ```

After applying those two patches the bounds are how they were in 0.14.1.

**Comment by philipc** [comment]
> let sup = match sections.sup.take() {

I don't think we can do this because `sections.sup` may be needed while later parsing entries in `sections`. It's one reason why `Arc` is being used. I did investigate if we could avoid the multiple references by embedding the `addr2line::ResDwarf` in `gimli::Dwarf`. This requires making `Dwarf::sup` generic over `AsRef<Dwarf<R>>` so that it could have the type `Option<Box<ResDwarf<R>>>`, but I don't think that's possible with rust currently.

Another option is to pass a `sup` parameter to every `Dwarf` method that needs it, but that's really ugly.

The other reason that `Arc` is used is that in theory `Dwarf::sup` could be shared between multiple `Context` (the point of supplementary object files is to contain information that is common to multiple binaries), and likewise for `ResDwarf::sup` but it's probably less important. This isn't used anywhere yet though.

**Comment by koute** [comment]
> I don't think we can do this because `sections.sup` may be needed while later parsing entries in `sections`.

That's what I though. Hm... as an alternative couldn't we simply just remove the `sup` field in `ResDwarf`, and instead use `sections.sup` directly?

> The other reason that `Arc` is used is that in theory `Dwarf::sup` could be shared between multiple `Context` (the point of supplementary object files is to contain information that is common to multiple binaries), and likewise for `ResDwarf::sup` but it's probably less important. This isn't used anywhere yet though.

Maybe it'd make sense to let the user decide whenever to use an `Arc` or not by having an extra generic argument? (Not sure how much noisier that would make everything due to the extra bounds; might not be worth it.)

**Comment by philipc** [comment]
> That's what I thought. Hm... as an alternative couldn't we simply just remove the sup field in ResDwarf, and instead use sections.sup directly?

No, because we also need to be able to search units in the supplementary object file, so we need an instance of `ResDwarf` that has its `ResDwarf::sections` field set to the original `sections.sup`.

> Maybe it'd make sense to let the user decide whenever to use an Arc or not by having an extra generic argument? (Not sure how much noisier that would make everything due to the extra bounds; might not be worth it.)

Right, but that's the same problem as allowing the user to decide to use a `ResDwarf`. Abstracting over `Arc` is hard. [`archery`](https://github.com/orium/archery) is a possible solution but I don't want to use it if `Arc` is good enough.

Is requiring `Reader: Sync + Send` a problem for your use?

**Comment by koute** [comment]
> Is requiring `Reader: Sync + Send` a problem for your use?

As far as I can see it shouldn't be a problem for me personally. What I care the most is to be able to have a `Mutex<Context>` that I can share between multiple threads.
