### ISSUE TITLE
osx binary 

### ISSUE THREAD

**Issue by pannous** [gimli-rs/addr2line#234]
is there a precompiled osx binary or package?
how would one compile it themself?

**Comment by bjorn3** [comment]
If you have the [rust compiler](https://www.rust-lang.org/learn/get-started) installed, you can use `cargo build --release --example addr2line` within a clone of this repo to build it to the `target/release/example` directory. The executable can be copied anywhere and you can delete the clone of this repo afterwards. It doesn't require any library not already installed on macOS by default.

There are no precompiled executables AFAICT.

**Comment by mstange** [comment]
You can also run the following command without needing to clone this repo:

```
cargo install --examples addr2line
```

This compiles addr2line and puts it at `~/.cargo/bin`.

**Comment by pannous** [comment]
thanks!
