### ISSUE TITLE
Duplicated `comp-dir`

### ISSUE THREAD

**Issue by Swatinem** [gimli-rs/addr2line#238]
When building a simple rust program with `--remap-path-prefix $PWD=root-comp-dir`, that results in the following DWARF:

```
# CU (llvm-dwarfdump output):
0x0000000b:   DW_TAG_compile_unit
                DW_AT_producer	("clang LLVM (rustc version 1.56.1 (59eed8a2a 2021-11-01))")
                DW_AT_language	(DW_LANG_Rust)
                DW_AT_name	("simple.rs")
                DW_AT_stmt_list	(0x00000000)
                DW_AT_comp_dir	("root-comp-dir/")
                DW_AT_GNU_pubnames	(true)
                DW_AT_low_pc	(0x00000000000010f0)
                DW_AT_high_pc	(0x00000000000010f9)
0x0000002f:     DW_TAG_subprogram
                  DW_AT_low_pc	(0x00000000000010f0)
                  DW_AT_high_pc	(0x00000000000010f9)
                  DW_AT_frame_base	(DW_OP_reg7 RSP)
                  DW_AT_name	("simple_fn")
                  DW_AT_decl_file	("root-comp-dir/simple.rs")
                  DW_AT_decl_line	(2)
                  DW_AT_external	(true)

# Line Table:

Line table prologue:
          format: DWARF32
         version: 4
file_names[  1]:
           name: "simple.rs"
      dir_index: 0
```

The above example is using `llvm-dwarfdump`, which seems to get this right.

However, `addr2line` duplicates the `comp-dir`:

```
> /usr/bin/addr2line -i -e simple.debug 0x10f2
root-comp-dir//simple.rs:5
> ~/.cargo/bin/addr2line -i -e simple.debug 0x10f2
root-comp-dir/root-comp-dir/simple.rs:5
```

My system `addr2line` does not duplicate the comp-dir, but has problems when joining the paths it seems.

I think the root cause is that `LineProgramHeader::directory` is defined in such a way that it returns the `comp_dir` for index 0, but that is then unconditionally concatenated to the comp dir, similar to here:

https://github.com/gimli-rs/gimli/blob/fdd7ee4ed4c58bee9b79ffdc895488b40a87c899/examples/simple_line.rs#L71-L73

See: https://docs.rs/gimli/0.26.1/gimli/read/struct.LineProgramHeader.html#method.directory

I can get a PR up to fix this next week.

**Comment by philipc** [comment]
Note that while I'm fine with fixing this issue, I don't think that using a relative path for `DW_AT_comp_dir` is valid.
