### ISSUE TITLE
Promote the CLI example to a `bin` crate

### ISSUE THREAD

**Issue by ishitatsuyuki** [gimli-rs/addr2line#245]
As stated in #244, there are some use cases where an addr2line replacement can be greatly useful.

Please consider promoting the example to a `bin` crate (by moving to `src/main.rs`), which allows it to be more easily installed through `cargo install`.

**Comment by philipc** [comment]
We'll probably want to move it into its own crate, so that it can have its own dependencies.

**Comment by mstange** [comment]
This is a good idea, but note that you can use `cargo install` today: `cargo install --examples addr2line`
