### ISSUE TITLE
No line information found in jitted-1234-56.so files generated by perf inject --jit

### ISSUE THREAD

**Issue by mstange** [gimli-rs/addr2line#248]
No filename and line number is found in [this jitted-103168-33.so](https://storage.googleapis.com/profiler-get-symbols-fixtures/jitted-103168-33.so):

```
% addr2line -pCfi 0x82 --exe jitted-103168-33.so  
IC: GlobalNameValue at ??:?
```

This .so has a rather minimal set of dwarf information, generated by [perf/util/genelf_debug.c](https://elixir.bootlin.com/linux/v5.17.9/source/tools/perf/util/genelf_debug.c#L434).
The single unit has no low pc / high pc information, so addr2line collects no unit ranges, so all address lookups fail immediately because no unit is found.

These .so files are produced by [`perf inject --jit`](https://github.com/torvalds/linux/blob/master/tools/perf/Documentation/perf-inject.txt) after using perf to profile applications with [JITDUMP](https://github.com/torvalds/linux/blob/master/tools/perf/Documentation/jitdump-specification.txt) support.

**Comment by mstange** [comment]
GNU binutils addr2line finds the filename + line number successfully.
LLVM addr2line does not find the information.

This difference in behavior also seems to apply to `objdump -S`; llvm-objdump does not show source code for this file.

**Comment by philipc** [comment]
Given that LLVM doesn't handle this either, is changing `perf` an option?

**Comment by mstange** [comment]
I think that's worth doing regardless; these .so files are weird in other ways too (no segments, and all sections start at address zero). But I have no experience with or ties to the perf project.

The reason I ran into this is that I was trying to write a faster replacement for `perf script` and it would be nice if it worked even with files created by existing perf versions.

**Comment by philipc** [comment]
So to fix here, if there are no ranges in the unit, I think we need to parse all the functions immediately. That'll be a small performance hit if the units really are empty, but these units should be rare enough and small enough that I doubt it matters.

**Comment by mstange** [comment]
There are no functions in these files either, just lines. The function names come from the symbol table.
I'll try what you said but with parsing the line program eagerly if there are no ranges in the unit. Then we can take the ranges from the line sequence start and end addresses.
