### ISSUE TITLE
Can't resolve libc symbol - which is found by C addr2line

### ISSUE THREAD

**Issue by Matthias247** [gimli-rs/addr2line#250]
I'm trying to reverse lookup a symbols based on addresses using this library. While it works for a Rust executable, I had less luck with a C `.so`. 

One example I wanted to lookup was the `__sendmmsg` function.

objdump shows the address at 0x123d90:
```
objdump -t -T /usr/lib/x86_64-linux-gnu/libc-2.31.so | grep __sendmmsg
0000000000123d90 g    DF .text  00000000000000a5  GLIBC_PRIVATE __sendmmsg
```

Ubuntu addr2line finds the symbol:
```
addr2line -e  /usr/lib/x86_64-linux-gnu/libc-2.31.so -f -i -a 123d90
0x0000000000123d90
__sendmmsg
??:?
```

But gimli-rs/addr2line can't find it:
```
cargo run --example addr2line -- --exe  /usr/li
b/x86_64-linux-gnu/libc-2.31.so -f -i -a 123d90
0x0000000000123d90
??
??:0
```

In case it matters for reproduction: I'm running this on WSL2 with a Ubuntu 20.4 distribution

**Comment by philipc** [comment]
This is a bug in the `object` crate. [`symbol_table`](https://github.com/gimli-rs/object/blob/3fe732e7dc0453953d83e0f62eb256d5fc78a460/src/read/elf/file.rs#L266) always returns `Some`, which means it never falls back to `dynamic_symbol_table` if the debugging symbol table is empty.

However, even if that is fixed, addr2line won't provide very good results without DWARF debugging information (whether this crate or the Ubuntu version of addr2line). I suggest that if you want to look up addresses in libc then you install the debug package for it and use that.

**Comment by philipc** [comment]
Oh, and note that the `addr2line` library itself doesn't use symbol tables at all. It's only in the example that they are used.
