### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mstange** [gimli-rs/addr2line#252]
Hi, I'd be interested in a release of addr2line which includes the DWARF 5 compat fix.

**Comment by philipc** [comment]
Sure, I'll do that soon.

I'm thinking of deprecating `Context::new` for this release, and removing it in the next (#253). Thoughts?

**Comment by mstange** [comment]
Sounds good to me! I don't use `Context::new` for the reason you mentioned: copying the data into an `EndianRcSlice` (around 1GB for libxul.so IIRC) is not good for performance. And removing the `object` dependency would be a nice benefit. I agree that it would be better to move the convenience APIs to a separate crate.

**Comment by mstange** [comment]
Thanks!
