### ISSUE TITLE
Tests are failing with nightly rust due to packed debuginfo

### ISSUE THREAD

**Issue by philipc** [gimli-rs/addr2line#256]
Currently the tests require Linux builds to use `split-debuginfo=off` and macOS builds to use `split-debuginfo=packed`. On stable rust, we achieve this with `split-debuginfo=packed` in `Cargo.toml`. This works because this option is only supported for macOS. However, nightly rust has stabilized this option for Linux as well, and so now CI is failing.

I can't see how to specify platform specific options in profiles. For example, I would expect something like this to work, but it doesn't:
```
[target.'cfg(macos)'.profile.test]
split-debuginfo = 'packed'
```

@davidtwco Do you know how to achieve this? Is it intended that all platforms must use the same `split-debuginfo` settings?

**Comment by bjorn3** [comment]
macOS defaults to packed for back compat reasons, so not setting split-debuginfo at all should work.

**Comment by philipc** [comment]
Hmm, can't test that now, but the reason I had this in the first place is because it was defaulting to unpacked.

**Comment by bjorn3** [comment]
Right, cargo changed the default in https://github.com/rust-lang/cargo/pull/9298. My bad.

**Comment by philipc** [comment]
The relevant cargo issue is https://github.com/rust-lang/cargo/issues/4897

We can use environment variables to work around this in CI, but the cargo setting would still be preferred.
