### ISSUE TITLE
Broken with clang-16 debug info on Linux

### ISSUE THREAD

**Issue by abique** [gimli-rs/addr2line#272]
Hi,

It currently fails to read debug info produced by clang-16.
I suspected the introduction of zstd to be the cause but apparently not, I've tried with `-gz=zlib` and it didn't improve the situation.

I suppose that the issue resides at a lower level of the stack; maybe upgrading addr2line's dependencies would fix it?

Cheers,
Alex

**Comment by philipc** [comment]
I tried with a simple hello world program and it was ok.

Can you provide a file produced by clang-16 and the command you are running?

**Comment by abique** [comment]
Hi,
I've continued my investigation and I found that the problem was elsewhere.
Please excuse me for the invalid but report.
Cheers,
Alex
