### ISSUE TITLE
How to locate a symbol using this crate?

### ISSUE THREAD

**Issue by noneback** [gimli-rs/addr2line#282]
I am trying to find symbols of shared object files using relative addresses.

I have a relative address `0x29d90`

using `addr2line`, the linux cmdline tool, I got this:
```bash
addr2line -e /usr/lib/x86_64-linux-gnu/libc.so.6 -a 0x29d90
0x0000000000029d90
./csu/../sysdeps/nptl/libc_start_call_main.h:58
```
However, I got an empty result using the example in the repository, `examples/addr2line`. 

```bash 
./target/debug/examples/addr2line  --exe /usr/lib/x86_64-linux-gnu/libc.so.6 0x29d90
??:0
```

So, I am wondering how to locate a symbol using this crate.   I noticed that the doc embedded in the source code, says the arg `probe` is a virtual address. I also try to pass the process virtual address to find symbols, but it still doesn't work.

**Comment by philipc** [comment]
This crate doesn't attempt to locate DWARF that is in a separate file (often somewhere under `/usr/lib/debug/` for system files). You'll need to locate that file yourself and specify it instead of the executable.

**Comment by noneback** [comment]
> This crate doesn't attempt to locate DWARF that is in a separate file (often somewhere under `/usr/lib/debug/` for system files). You'll need to locate that file yourself and specify it instead of the executable.

Would you mind show me some codes or function's usage in detail? I am actually confused about `probe` in those find_xxxxx(probe) function signatures. What does the `virtual address` mean?

**Comment by philipc** [comment]
The code in the `addr2line` example shows how to use it. If you want something that also locates the DWARF then you could look at https://github.com/rust-lang/backtrace-rs/blob/master/src/symbolize/gimli/elf.rs. Also see https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

Virtual address has the same meaning as the address that the linux cmdline tool accepts.

**Comment by noneback** [comment]
Thx!
