### ISSUE TITLE
addr2line should use .symtab information

### ISSUE THREAD

**Issue by philipc** [gimli-rs/addr2line#3]
In the absence of `.debug_line` information, there is still other file and address information in `.debug_info` that we can use to give vague information about the address.

**Comment by philipc** [comment]
Not sure this actually occurs in practice. But what does happen is there are filenames and symbol names in the '.symtab' section that we should use. This matches the original case that caused the issue to be reported in gimli.

**Comment by Arkanosis** [comment]
In the case mentioned in #55, binutils' addr2line uses the symbol names found in the `.strtab` section (elf64).
