### ISSUE TITLE
Support byte based API ?

### ISSUE THREAD

**Issue by m4b** [gimli-rs/addr2line#37]
I would like to use this in an application but it seems the only entry point in the API is a path based one. 

Do you plan on supporting an `AsRef<[u8]>` or  a simple &[u8] entry point ?

As it stands now the API as is would essentially double memory usage for a consumer which has already loaded / obtained the bytes in some lawful (or unlawful) manner, as it appears to memmap the binary/bytes. 

Thanks and awesome crate!

**Comment by fitzgen** [comment]
Thanks for the kind words :)

We would need multiple such entry points, one for each DWARF section that we need:

* `.debug_line`
* `.debug_info`
* `.debug_abbrev`
* `.debug_str`
* `.debug_ranges`

See https://github.com/gimli-rs/addr2line/blob/master/src/lib.rs#L269-L281

Right now we use the `object` crate, but have talked about using `goblin` before instead (for all of `gimli`'s object file interaction). The thing holding us back thus far has been the lack of zero-copy + mmap support in `goblin`. Although there has also been talk of moving away from that approach because of virtual address space exhaustion on 32 bit architectures, but there isn't a clear resolution there yet. The other thing was that mach-o support seemed incomplete at the time. I just mention `goblin` because I see you're the author ;)

All that said, I'd be open to an API that took all those sections as `&[u8]` or `AsRef<u8>` generic parameters.

@jonhoo @philipc what do you think?

**Comment by philipc** [comment]
I think an API that takes `&[u8]` sections makes sense. Even if gimli changes to using a `Reader`, we'll still be able to maintain a `&[u8]` API on top of that as well.

**Comment by m4b** [comment]
> Right now we use the object crate, but have talked about using goblin before instead (for all of gimli's object file interaction).

That would be awesome ! So just released 0.0.8. The API has been made significantly less complicated (imho), especially the various `parse` signatures, and the source code hopefully easier to read (as someone complained about this)

> The thing holding us back thus far has been the lack of zero-copy + mmap support in goblin.

This is understandable. For memmap I don't really see an issue, as the "parser" API supports loading from ` AsRef<[u8]>` so if something has been memmapped the client should be able to provide the bytes directly to `goblin::elf::Elf::parse`. Unless I'm misunderstanding? This might not have been clear before as 0.0.7 was a total disaster of a release API wise, and 0.0.6 before that only used Read based API iirc. 

Zero-copy on the other hand is somewhat of a thorny issue. So goblins "endian_fd" feature parses the bytes in foreign endianness, and works well, e.g., I've been testing [bingrep](https://github.com/m4b/bingrep) on openrisc binaries (on my x86_64 machine), which are 32-bit big endian. 

I haven't examined your dwarf implementation enough but I can't see how you can't "copy", e.g., reinterpet the underlying bytes as a big endian/little endian integer, etc.  This is what byteorder does under the hood, e.g. the integer isn't backed in some sense by the bytes it came from, etc.

The elf structs are also meant to be C abi compatible so I don't do anything fancy (like back then with a byte buffer), as they're meant to be used in no std situations, etc. 

There are places in goblin which definitely copy when they don't necessarily need to, but I don't think it's too big a bottleneck.

Likely the larger problem is that the "built in" goblin parser eagerly parses everything, relocations, etc., which might never be used for the client. This will be a problem, e.g. parsing the chromium binary has 400k relocations which takes some time (not really though, on my machine it's about 150 ms) and might never be used. 

I have a solution for this but I'm hesitant to use it because the Elf struct right now is so simple and easy to use I don't know if it'll be a benefit. 

If you have any ideas or suggestions please fee free to open an issue or chip in somewhere I'm definitely open to improving the use cases, the API surface, etc.

> Mach-o support seemed incomplete 

Yuppppp :sob: I haven't noticed much demand so I kept putting it off, as I've been working on giving the ELF API amenable to an external `Write` implementation. 

I will start working on this, as I should just finish it up

Lastly, and excuse my ignorance about dwarf stuff, for the debug sections are those 5 sections always called that? Like is that how gdb, etc always accesses the debug info, regardless of platform ?  If so I could easily add a method somewhere which given a section list and some bytes returns the an array of five options byte slices into the debug info, or something like that. 

Anyway this was a long response, sorry, and keep up the good work !

**Comment by tromey** [comment]
> Like is that how gdb, etc always accesses the debug info, regardless of platform ?

Unfortunately not.  gdb might also look for the sections under their compressed names, like `.zdebug_info`.  There's also `.debug_info.dwo`, which is part of DWARF Fission; I don't know a whole lot about that, but it's been finalized in DWARF 5 now so you could read about it there.  Also on Mach-O, BFD remaps the names, so when gdb tries to read (e.g.) `.debug_info`, BFD will actually read `__debug_info`.

There are also more than 5 debug sections, I think gimli just doesn't try to read more than that yet.  gdb supports at least 16, maybe 17.  Some of these may be obsolete (like `.debug_types` was, I think, removed in DWARF 5).

**Comment by tromey** [comment]
Oh, I almost forgot, for XCOFF systems (AIX), the name mapping is done in gdb, not BFD (dunno why the difference).  XCOFF uses names like `.dwinfo`, and doesn't support the full suite of debug sections.  Not sure if you're planning to deal with XCOFF but I figured it was worth a mention anyhow.

**Comment by fitzgen** [comment]
> Also on Mach-O, BFD remaps the names, so when gdb tries to read (e.g.) .debug_info, BFD will actually read __debug_info.

FWIW, `object` does this too.

**Comment by fitzgen** [comment]
> For memmap I don't really see an issue, as the "parser" API supports loading from AsRef<[u8]> so if something has been memmapped the client should be able to provide the bytes directly to goblin::elf::Elf::parse. Unless I'm misunderstanding?

I must have missed something, or it didn't exist back then.

> I haven't examined your dwarf implementation enough but I can't see how you can't "copy", e.g., reinterpet the underlying bytes as a big endian/little endian integer, etc. This is what byteorder does under the hood, e.g. the integer isn't backed in some sense by the bytes it came from, etc.

Yes, it isn't 100% true. We do avoid copying many things in two ways:

* We lazily parse DIE entries / line number program opcodes / etc. If they're never used, they're never copied.
* Various strings and length-prefixed blocks are true zero-copy

> Likely the larger problem is that the "built in" goblin parser eagerly parses everything, relocations, etc., which might never be used for the client. This will be a problem, e.g. parsing the chromium binary has 400k relocations which takes some time (not really though, on my machine it's about 150 ms) and might never be used.

We currently punt on relocations, and I'm not eager to implement them. Judging from the lack of PRs, it seems no one else is eager either ;)

> Lastly, and excuse my ignorance about dwarf stuff, for the debug sections are those 5 sections always called that? Like is that how gdb, etc always accesses the debug info, regardless of platform ? If so I could easily add a method somewhere which given a section list and some bytes returns the an array of five options byte slices into the debug info, or something like that.

Those 5 sections are just the ones we happen to use for `addr2line`. A profiler or debugger could use a different set.

Also, as @tromey mentioned, there are sections that are logically the same but have different names on different platforms and object file formats. Hiding this under some kind of abstraction would be 💯

**Comment by m4b** [comment]
ping! So are there still plans to expose a `&[u8]` api?  I want to add this as a crate library to a couple of projects where I simply give it/the api a `u64/usize` and a `&[u8]` and ideally it returns the corresponding line in the source code.

It's important though that I don't have to pass it a path to the executable, but simply raw bytes, as the executable in question is already loaded, and the bytes are ready.

Is this possible?

**Comment by philipc** [comment]
This should actually be pretty trivial to do. Basically we just need to change the existing `struct DebugInfo` to be public. Does that look like it would work for you?

We could also change the `DebugInfo:new()` so that it either takes `&[u8]` for the whole file, or `&[u8]` for the sections it requires. The first means it will use the `object` crate internally, the second means you can use whatever loader you want.

I may have time to work on this in the near future. I want to finish up doing a fews things in gimli and put out a new release of it first.

**Comment by m4b** [comment]
> Basically we just need to change the existing struct DebugInfo to be public. Does that look like it would work for you?

I'm not sure, I'd have to see the prospective API.  To be clear, something like this is what I had in mind:

```rust
let bytes = .. bytes of binary..
// do some stuff, unrelated to debugging, parse the binary, do other stuff, etc.
let debug_info = DebugInfo::new(bytes)?;
match debug_info.addr2line(some_address)? {
  Some(line) => // do stuff using this line,
  None => // do stuff when there isn't a line for the given address
}
```

a section based api would be cool too, but mostly for starters I'd like to experiment with something like the above.

Is something like this feasible?

**Comment by philipc** [comment]
> // do some stuff, unrelated to debugging, parse the binary, do other stuff, etc.

If you're already parsing the binary, wouldn't it be better to pass the result of that to addr2line?

Anyway, the existing API is:

```rust
fn new<'a>(file: &object::File<'a>, opts: Options) -> Result<DebugInfo<'a, Endian>>;
fn locate(&self, addr: u64) -> Result<Option<(path::PathBuf, Option<u64>, Option<Cow<str>>)>>;
```

If you want it to take `&[u8]`, then we could add:
```rust
fn from_u8_slice<'a>(file: &'a [u8], opts: Options) -> Result<DebugInfo<'a, Endian>>;
```

Note that for both of these we're assuming the caller has determined the correct `Endian`. Alternatively, we could change to using `RunTimeEndian`.

**Comment by m4b** [comment]
> If you're already parsing the binary, wouldn't it be better to pass the result of that to addr2line?

Ah yea, I forgot object uses goblin under the hood now; it doesn't seem to expose an interface for creating an `object::File` from a pre-parsed result though, so iiuc, passing raw bytes would reparse, yes?

So seems like there are 3 options:

1. expose `&[u8]` api which constructs the `object::File` object (potentially/probably again)
2. expose a `from`-esque method for converting a goblin object to a `object::File`, e.g., something like: `File::from_elf<'a>(goblin::elf::Elf<'a>, bytes: &'a [u8])`
3. expose section based byte api, for expert knowledge/manual debug parsing.

2. is probably the easiest, but it would leak your impl into the public api, which you probably wouldn't want.

I think I don't think I feel like dealing with 3. because iiuc, there is some magic/heuristics/platform issues for selecting the correct debug ranges, and this is really the job of the debug parser, yes?

So 1. seems to be the only viable choice, but I believe it will always reparse, which is a bummer. I basically want my cake and eat it too (no reparsing), but not sure how to accomplish this.

Do you see any way to allow raw byte based version, that doesn't reparse, and doesn't require manually understanding the backing debug sections of the bytes?

**Comment by m4b** [comment]
@philipc 

> Anyway, the existing API is:

Actually, I'm confused, looking at addr2line docs, the only api currently is the path based one (which in my case would not only reallocate the bytes, but also parse, which was original impetus for this issue), or did you mean that the addr2line future API would be what you specified?

**Comment by philipc** [comment]
I meant the existing [new](https://github.com/gimli-rs/addr2line/blob/6680e3d157575817c901e6679e51f1469a86b80c/src/lib.rs#L267) and [locate](https://github.com/gimli-rs/addr2line/blob/6680e3d157575817c901e6679e51f1469a86b80c/src/lib.rs#L306-L309) methods which would be available if we made `DebugInfo` public.

> there is some magic/heuristics/platform issues for selecting the correct debug ranges

Yes, see @tromey's comments above. Currently the only heuristics we implement are translating section names for Mach-O. There does need to be more, but nobody's cared enough to work on it yet. Once someone does work on that, we'll likely make changes to the API to support it.

To be clear, my suggestions above are unlikely to be an API that this crate provides in the long term. It's just something we could quickly do so that you can start using this crate now without loading the file twice. If there's no urgency on your part, then we could hold off until we have a better design, or if you want to work on this then that'd be great.

Long term, I think we want to provide an API that is independent of the object loader used. So the API is more likely to be something that requires `&[u8]` for the individual sections, or a function that maps a section ID to `&[u8]`.

**Comment by m4b** [comment]
Ok I think making DebugInfo public is probably the best approach at this point then, and will be 80% of what I want. Everything after that is just some perf additions

Unfortunately definitely don't have time to work on concrete changes for more robust API right now.
