### ISSUE TITLE
`addr2line` command should locate dSYMs on macOS

### ISSUE THREAD

**Issue by jonhoo** [gimli-rs/addr2line#5]
Currently, `addr2line` on macOS requires you to manually pass the path to the `dSYM` DWARF file, rather than the executable itself. It'd be neat if the `addr2line` command line tool could automatically figure this out for you. Related to #4.

**Comment by fitzgen** [comment]
See also https://github.com/gimli-rs/gimli/issues/154 and https://github.com/gimli-rs/moria

cc @kamalmarhubi

**Comment by kamalmarhubi** [comment]
ugh ugh so many things to do!!

**Comment by fitzgen** [comment]
No pressure! Just a heads up. It's not like anyone is paying you for your
time here ;)

**Comment by luser** [comment]
FWIW, since this was filed I have fleshed out enough of moria that it can locate dSYMs on mac. [Here's an example of using it](https://github.com/luser/rust-disasm/blob/b5be8d39d7fa9aae8704d9473952ddb65c039955/src/lib.rs#L297) in my rust-disasm crate.

**Comment by philipc** [comment]
Since this still hasn't been implemented here, and is not something I plan to do myself, I recommend using https://github.com/mstange/samply/tree/main/wholesym-addr2line instead.
