### ISSUE TITLE
publish 0.6

### ISSUE THREAD

**Issue by m4b** [gimli-rs/addr2line#76]
0.5 pulls in old object, which uses old goblin 0.0.10; there's been many improvements since then!

Also there's too many goblins hanging out in my `Cargo.lock` now ;)

**Comment by philipc** [comment]
A blocker for release is the unwind crate's dependency on a gimli fork.

@main-- This is only used for the correctness test. I see three options:
- get the gimli changes merged and published
- change the correctness test to use the backtrace crate (as done for the output equivalence test)
- delete the correctness test. Does it provide any value in addition to the output equivalence test?

Any preference? I don't have time to do the first option myself. The other options are trivial.

**Comment by main--** [comment]
The correctness test tests unwind as much as it tests addr2line. That crate is not really in a releasable state yet (needs more testing and platform support) so for now I wouldn't really want to depend on it anyways. The test exists mostly to compare to known-good values (unlike output equivalence, which arguably does something else) but now that I think about it, it can probably just go away. The only scenario it guards against is if an issue with the build process makes both GNU addr2line and ours return no data at all, thus preventing any actual testing - I don't think that's realistic however. On the other hand, it's susceptible to instabilities like #80 so this is probably not worth it.

**Comment by philipc** [comment]
Published 0.6.0.
