### ISSUE TITLE
#![no_std] support

### ISSUE THREAD

**Issue by est31** [gimli-rs/addr2line#90]
In order for addr2line to be integrated into libstd, it requires support for the `#![no_std]` environment. This also helps with integration into embedded programs and OS kernels.

**Comment by est31** [comment]
leaving this to @philipc as they said they had done work on this.

**Comment by philipc** [comment]
Dependencies need to be `#![no_std]` too. These are done:
- gimli
- fallible-iterator
- object
- intervaltree
- smallvec
- rustc-demangle

To do:
- [ ] lazy-init
- [ ] cpp_demangle

An alternative to lazy-init is https://github.com/indiv0/lazycell, but it doesn't have `no_std` support either.

**Comment by est31** [comment]
Thanks @philipc added lazy-init and cpp_demangle to #89. I'm giving cpp_demangle a shot.

**Comment by est31** [comment]
cpp_demangle supports `#![no_std]` now, see #89.

As for lazy-init: it uses a mutex internally, which doesn't seem to exist on libcore. lazycell on the other hand uses atomics, which do exist on libcore. So it should be easier to port lazycell.

**Comment by philipc** [comment]
Found one more: https://github.com/Storyyeller/stable_deref_trait/pull/2. This will need a gimli update too. Pretty sure that's the last of them though.

**Comment by est31** [comment]
Oh, probably this PR of mine won't compile successfully then: https://github.com/gimli-rs/gimli/pull/306
