### ISSUE TITLE
addr2line example should handle macos universal binaries

### ISSUE THREAD

**Issue by JunyiXie** [gimli-rs/addr2line#96]
iOS APP , dsym file

```
echo 0xFF1BE4 | ./addr2line  -s -i -f -p -a -e /Users/xiejunyi/Desktop/atosl/xxx.app.dSYM/Contents/Resources/DWARF/xxx
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Unknown file magic"', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by philipc** [comment]
Is that a multi-architecture (fat) binary? We don't currently handle them in the object crate. I don't think it would be hard to fix, but not something I've looked into. Contributions are welcome.

**Comment by philipc** [comment]
Try https://github.com/mstange/samply/tree/main/wholesym-addr2line instead.
